name: Goodbye Artur and Dawid
on:
  workflow_dispatch:
jobs:
  Goodbye:
    runs-on: ubuntu-latest
    steps:
      - name: Small speach
        run: |
          sleep 10
          echo -e "I see no better way to say goodbye, than making and Github Action for it "
          sleep 2
          echo -e "It's been awesome to work with you both"
          sleep 2
          echo -e "You will both be missed wery much!!!!!!"
          sleep 2
          echo -e "Not because your awesome people."
          sleep 2
          echo -e "But who the hell do you expect to cleanup our DevOps mess??? ğŸ’©"
          sleep 2
          echo -e "ğŸ™ˆ Kush?"
          sleep 2
          echo -e "ğŸ™‰ Matt??"
          sleep 2
          echo -e "ğŸ™Š Assem???"
          sleep 2
          echo -e "Sure as hell it's not going to be me ğŸ˜†"
          sleep 2
          echo -e "ğŸ˜ ( Looking at BjÃ¸rn )"
          sleep 2
          echo -e "ğŸ˜ ( Looking at BjÃ¸rn )"
          sleep 2
          echo -e "But yes, we will miss you both because your both awesome ğŸ˜"
          sleep 2
          echo -e "You have both helped this team so much"
          sleep 2
          echo -e "ğŸ„ I hope you both have a nice xmas and a happy new year.ğŸ¾"
          sleep 2
          echo -e "Wish you both best of luck and hope you both find some cool new projects to work on. ğŸš€"
          sleep 10
  Song:
    runs-on: ubuntu-latest
    steps:
      # Runs a set of commands using the runners shell
      - name: Song ğŸ¤
        run: |
          sleep 10
          echo -e "We're no strangers to love"
          sleep 2
          echo -e "You know the rules and so do I (do I)"
          sleep 2
          echo -e "A full commitment's what I'm thinking of"
          sleep 2
          echo -e "You wouldn't get this from any other guy"
          sleep 2
          echo -e " "
          sleep 2
          echo -e "I just wanna tell you how I'm feeling"
          sleep 2
          echo -e "Gotta make you understand"
          sleep 2
          echo -e " "
          sleep 2
          echo -e "Never gonna give you up"
          sleep 2
          echo -e "Never gonna let you down"
          sleep 2
          echo -e "Never gonna run around and desert you"
          sleep 2
          echo -e "Never gonna make you cry"
          sleep 2
          echo -e "I am gonna say goodbye ğŸ˜­"
          sleep 2
          echo -e "Never gonna tell a lie and hurt you"
          sleep 2
          echo -e " "
          sleep 2
          echo -e "(ï¾‰à²¥ç›Šà²¥ï¼‰ï¾‰ â”»â”â”»"
          echo -e " "
          sleep 2
          echo -e " "
          sleep 2
          echo -e " "
          sleep 2
          echo -e " "
          sleep 2
          echo -e " "
          sleep 2
          echo -e " "
          sleep 2
          echo -e " "
          sleep 2
          echo -e " "
          sleep 2
          echo -e " "
          sleep 2
          echo -e " "
          sleep 2
          echo -e " "
          sleep 2
          echo -e " "
          sleep 2
